---
- name: ensure all nodes have correct hostname
  hostname: 
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts remove stale IP entries
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item]['ansible_ssh_host'] }} (?!{{ item }}$)"
    state: absent
  with_items: "{{ groups['all'] }}"
  tags:
    - openstack-host-hostfile

- name: Update /etc/hosts remove stale Host entries
  lineinfile:
    dest: /etc/hosts
    regexp: "(?<!^{{ hostvars[item]['ansible_ssh_host'] }}) {{ item }}"
    state: absent
  with_items: "{{ groups['all'] }}"
  tags:
    - openstack-host-hostfile

- name: Update /etc/hosts file from ansible inventory
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_ssh_host'] }} {{ item }}"
    state: present
  with_items: "{{ groups['all'] }}"
  tags:
    - openstack-host-hostfile