---
- name: ensure user `neutron` present
  keystone:
    command: "ensure_user"
    user_name: "{{ neutron_service_identity_name }}"
    password: "{{ neutron_service_identity_password }}"
    state: present
    endpoint: "{{ openstack_keystone_endpoint }}"
    token: "{{ openstack_keystone_token }}"

- name: ensure neutron's user role present
  keystone:
    command: "ensure_role"
    role_name: admin
    state: present
    endpoint: "{{ openstack_keystone_endpoint }}"
    token: "{{ openstack_keystone_token }}"

- name: ensure neutron's user project present
  keystone:
    command: "ensure_project"
    project_name: "{{ neutron_service_identity_admin_project }}"
    state: present
    endpoint: "{{ openstack_keystone_endpoint }}"
    token: "{{ openstack_keystone_token }}"

- name: ensure admin role was assigned to neutron's user
  keystone:
    command: "ensure_user_role"
    user_name: "{{ neutron_service_identity_name }}"
    project_name: "{{ neutron_service_identity_admin_project }}"
    role_name: admin
    state: present
    endpoint: "{{ openstack_keystone_endpoint }}"
    token: "{{ openstack_keystone_token }}"