---
- name: update apt database
  apt:
    update_cache: yes
    cache_valid_time: 3600
  register: apt_update
  until: apt_update|success
  retries: 5
  delay: 2

- name: install cinder-api related packages
  apt:
    name: "{{ item }}"
    state: latest
  register: install_package
  until: install_package|success
  retries: 5
  delay: 2
  with_items: cinder_api_apt_packages
  when: inventory_hostname not in groups['cinder_volume']

- name: install cinder-volume related packages
  apt:
    name: "{{ item }}"
    state: latest
  register: install_package
  until: install_package|success
  retries: 5
  delay: 2
  with_items: cinder_volume_apt_packages
  when: inventory_hostname in groups['cinder_volume']