---
- name: ensure cinder.conf config file up-to-date
  template:
    src: "cinder.conf.j2"
    dest: "/etc/cinder/cinder.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: inventory_hostname not in groups['cinder_volume']
  notify:
    - restart cinder-api services

- name: ensure cinder.conf config file up-to-date
  template:
    src: "cinder.conf.j2"
    dest: "/etc/cinder/cinder.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: inventory_hostname in groups['cinder_volume']
  notify:
    - restart cinder-volume services