---
# Openstack image apt packages
glance_apt_packages:
  - glance
  - python-glanceclient

glance_keystone_auth_plugin: password
glance_service_region: "{{ openstack_services_region }}"
glance_service_name: glance
glance_service_description: "OpenStack Image service"
glance_service_type: image
glance_service_port: "{{ glance_service_port }}"
glance_service_bind: 0.0.0.0
glance_service_proto: http
glance_service_publicurl: "{{ glance_service_proto }}://{{ glance_service_public_ip }}:{{ glance_service_port }}"
glance_service_internalurl: "{{ glance_service_proto }}://{{ glance_service_internal_ip }}:{{ glance_service_port }}"
glance_service_adminurl: "{{ glance_service_proto }}://{{ glance_service_public_ip }}:{{ glance_service_port }}"

glance_registry_service_port: 9191
glance_registry_service_bind: 0.0.0.0