---

- name: wait for keystone admin to come up
  wait_for:
    host: "{{ openstack_identity_public_ip }}"
    port: "{{ openstack_keystone_admin_port }}"
    timeout: 25
    delay: 0
  connection: local

- name: ensure image service
  keystone:
    command: 'ensure_service'
    service_name: "{{ glance_service_name }}"
    description: "{{ glance_service_description }}"
    service_type: "{{ glance_service_type }}"
    state: present
    endpoint: "{{ openstack_keystone_endpoint }}"
    token: "{{ openstack_keystone_token }}"

- name: ensure identity endpoint exists
  keystone:
    command: 'ensure_endpoint'
    service_name: "{{ glance_service_name }}"
    region_name: "{{ glance_service_region }}"
    service_type: "{{ glance_service_type }}"
    state: present
    endpoint_list:
      publicurl: "{{ glance_service_publicurl }}"
      adminurl: "{{ glance_service_adminurl }}"
      internalurl: "{{ glance_service_internalurl }}"
    endpoint: "{{ openstack_keystone_endpoint }}"
    token: "{{ openstack_keystone_token }}"
